### ISSUE TITLE
Garbage collection, improving the efficiency of memory use

### ISSUE THREAD

**Issue by GlebSBrykin** [mashmawy/FastStyleTransfer#1]
I have studied your implementation and am very pleased. However, I noticed that processing even a very small image takes a lot of RAM. I determined that to correct the situation, unused feature maps should be destroyed after each layer has passed. It is possible to prescribe in the implementation of TransformNet. I have already done the styling with such a network and checked how important the timely release of memory.

Here is a link to my implementation: https://github.com/PABCSoft/ImageStyler

And here You can find huge pictures: https://github.com/jcjohnson/fast-neural-style/issues/161

I am sure you will easily do it and get great results.

**Comment by mashmawy** [comment]
there is a lot of improvement to implement
