### ISSUE TITLE
Training of custom styles and optical flow

### ISSUE THREAD

**Issue by ad48hp** [mashmawy/FastStyleTransfer#2]
Could ya implement training of custom styles, so i wouldn't be restricted just to these ? (or at least tell, if it can be done by other software/scriptz),
Also, secondly as a lower weight request, it would be najz if there was multi-image processing, and possibly optical flow between these.
I might look at the multi-image proc. myself (_not at the flow though_)..

**Comment by mashmawy** [comment]
sorry for the late respond, actually ii tried to implement custom style trainer, check this issue
https://github.com/mashmawy/AlbiruniML/issues/1

check this
[SqueezeNetModel.zip](https://github.com/mashmawy/AlbiruniML/files/2613310/SqueezeNetModel.zip)
